import type { Product } from "@/types"

// Datos de muestra para inicializar la base de datos
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Molde de Silicona para Cupcakes",
    description: "Molde de silicona de alta calidad para 12 cupcakes. Resistente al calor hasta 230°C.",
    price: 15.99,
    stock: 25,
    category: "moldes",
    imageUrl: "/placeholder.svg?height=300&width=300",
    featured: true,
  },
  {
    id: "2",
    name: "Colorante Alimentario Azul",
    description: "Colorante alimentario azul intenso. Ideal para decoración de pasteles y glaseados.",
    price: 4.99,
    stock: 50,
    category: "colorantes",
    imageUrl: "/placeholder.svg?height=300&width=300",
    featured: true,
  },
  {
    id: "3",
    name: "Batidora de Mano Profesional",
    description: "Batidora de mano profesional con 5 velocidades. Potencia de 300W.",
    price: 89.99,
    stock: 10,
    category: "utensilios",
    imageUrl: "/placeholder.svg?height=300&width=300",
    featured: true,
  },
  {
    id: "4",
    name: "Harina de Repostería Premium",
    description: "Harina de repostería de alta calidad. Paquete de 1kg.",
    price: 3.49,
    stock: 100,
    category: "ingredientes",
    imageUrl: "/placeholder.svg?height=300&width=300",
    featured: true,
  },
  {
    id: "5",
    name: "Set de Boquillas para Decoración",
    description: "Set de 24 boquillas para decoración de pasteles y cupcakes.",
    price: 19.99,
    stock: 15,
    category: "decoracion",
    imageUrl: "/placeholder.svg?height=300&width=300",
    featured: false,
  },
  {
    id: "6",
    name: "Molde para Tartas Desmontable",
    description: "Molde para tartas desmontable de 26cm de diámetro. Antiadherente.",
    price: 12.99,
    stock: 20,
    category: "moldes",
    imageUrl: "/placeholder.svg?height=300&width=300",
    featured: false,
  },
  {
    id: "7",
    name: "Esencia de Vainilla Natural",
    description: "Esencia de vainilla 100% natural. Botella de 100ml.",
    price: 8.99,
    stock: 30,
    category: "ingredientes",
    imageUrl: "/placeholder.svg?height=300&width=300",
    featured: false,
  },
  {
    id: "8",
    name: "Termómetro Digital para Repostería",
    description: "Termómetro digital con sonda para repostería. Rango de -50°C a 300°C.",
    price: 14.99,
    stock: 5,
    category: "utensilios",
    imageUrl: "/placeholder.svg?height=300&width=300",
    featured: false,
  },
]
